name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Deploy to EC2
        run: |
          npm run build
          scp -i <(echo "$EC2_PRIVATE_KEY") -r ./dist ec2-user@ec2-3-214-28-97.compute-1.amazonaws.com:/home/ec2-user/hackerconnect-backend
        env:
          EC2_USER: ec2-user
          EC2_PUBLIC_IP: ec2-3-214-28-97.compute-1.amazonaws.com
